name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm@6.11.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier --check .
      # - run: printenv ENV_TS | base64 -d > src/env.ts
      #   env:
      #     ENV_TS: ${{ secrets.ENV_TS }}
      # - run: pnpm prisma generate
      - run: pnpm tsc --noEmit
      - run: pnpm test
