name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g pnpm@6.10.2
      - run: pnpm i --frozen-lockfile
      - run: pnpx prettier --check . --ignore-path .gitignore
      - run: printenv ENV_TS | base64 -d > src/env.ts
        env:
          ENV_TS: ${{ secrets.ENV_TS }}
      - run: pnpm run prisma:generate
      - run: pnpx tsc --noEmit
